# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano_v2
    shield: senyatyl_left
  - board: nice_nano_v2
    shield: senyatyl_left
    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_LOG_BUFFER_SIZE=32768
    artifact-name: senyatyl_left_debug-nice_nano_v2-zmk
  - board: nice_nano_v2
    shield: senyatyl_right
  - board: nice_nano_v2
    shield: senyatyl_right_peripheral
  - board: nice_nano_v2
    shield: senyatyl_right_peripheral
    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_LOG_BUFFER_SIZE=32768
    artifact-name: senyatyl_right_peripheral_debug-nice_nano_v2-zmk
  - board: seeeduino_xiao_ble
    shield: senyatyl_dongle prospector_adapter
    artifact-name: senyatyl_dongle-seeeduino_xiao_ble-zmk
  - board: seeeduino_xiao_ble
    shield: senyatyl_dongle prospector_adapter
    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_LOG_BUFFER_SIZE=32768
    artifact-name: senyatyl_dongle_debug-seeeduino_xiao_ble-zmk
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: settings_reset-seeeduino_xiao_ble-zmk
