file_format: "1"
id: senyatyl
name: Senyatyl
type: shield
requires: [pro_micro]
features:
  - keys
  - pointer
siblings:
  - senyatyl_left
  - senyatyl_right
  - senyatyl_right_nomouse
  - senyatyl_right_col2row
  - senyatyl_right_peripheral
