CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_MOUSE=y

CONFIG_PMW3360=y
CONFIG_PMW3360_CPI=400
CONFIG_PMW3360_CPI_DIVIDOR=1
CONFIG_PMW3360_SNIPE_CPI=200
CONFIG_PMW3360_SNIPE_CPI_DIVIDOR=1
CONFIG_PMW3360_ORIENTATION_90=y
CONFIG_PMW3360_INVERT_Y=y
