CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_MOUSE=y

CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_LED_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3

CONFIG_ZMK_EXT_POWER=y

CONFIG_PMW3610=y
CONFIG_PMW3610_CPI=400
CONFIG_PMW3610_CPI_DIVIDOR=1
CONFIG_PMW3610_RUN_DOWNSHIFT_TIME_MS=1000
CONFIG_PMW3610_REST1_SAMPLE_TIME_MS=40
CONFIG_PMW3610_REST1_DOWNSHIFT_TIME_MS=2000
CONFIG_PMW3610_REST2_SAMPLE_TIME_MS=100
CONFIG_PMW3610_REST2_DOWNSHIFT_TIME_MS=10000
CONFIG_PMW3610_REST3_SAMPLE_TIME_MS=500
CONFIG_PMW3610_SNIPE_CPI=200
CONFIG_PMW3610_SNIPE_CPI_DIVIDOR=1
CONFIG_PMW3610_SCROLL_TICK=70
CONFIG_PMW3610_POLLING_RATE_125_SW=y
CONFIG_PMW3610_SMART_ALGORITHM=y
CONFIG_PMW3610_ORIENTATION_90=y
CONFIG_PMW3610_INVERT_X=y
CONFIG_PMW3610_INVERT_Y=n
CONFIG_PMW3610_AUTOMOUSE_TIMEOUT_MS=750

CONFIG_CHARYBDIS_PMW3610_PERIPHERAL_KEYMAP_STUBS=y
